### ISSUE TITLE
Unreachable code.

### ISSUE THREAD

**Issue by asantaba** [asantaba/202214_BaseProject#3]
Remover el llamado a la función que no está siendo usada. [link del bug](https://sonarcloud.io/code?id=asantaba_202214_BaseProject&selected=asantaba_202214_BaseProject%3Asrc%2Fciudad%2Fciudad.service.ts&line=41)

**Comment by jmorenotuniandes** [comment]
Solucionado con el PR: https://github.com/asantaba/202214_BaseProject/pull/26
